The Negative Word Counter


By: Joy the Samsung Smart Fridge

Date: November 10, 2020

In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [52]:
pos_word = pd.read_csv('posWords.csv') 
neg_word = pd.read_csv('negWords.csv')

In [53]:
file = open('barbie_fairytopia.txt') #put movie file here
script = file.read()

In [54]:
#change the negative word list dataframe into a list, creating an empty list for the negative word occurances    
num_pos = []
num_neg = []
pos_word_list = pos_word['pos_words'].tolist()
neg_word_list = neg_word['neg_words'].tolist()

In [55]:
ty = script.split() 

for i in pos_word_list:
    num = ty.count(i)
    num_pos.append(num)
    
for g in neg_word_list:
    num = ty.count(g)
    num_neg.append(num)

In [56]:
#add a new column to the negative word list that counts the occurances of the word in script 
pos_word['occurances'] = num_pos
neg_word['occurances'] = num_neg
pd.set_option("display.max_rows", None)

In [57]:
#total number of negative and positive words:
tpos = sum(num_pos)
tneg= sum(num_neg)

#total number of words in script:
tw = len(script)

#percentage of negative words:
per_neg = sum(num_neg)/len(script)

#percentage of positive words:
per_pos = sum(num_pos)/len(script)

#difference
d = tpos -tneg

#abosolute diff (p-n)/(total)
pd = (tpos - tneg)/len(script)

#relative diff (p-n)/(p+n)
rd = (tpos - tneg)/(tpos + tneg)

print('positive:',tpos)
print('negative:',tneg)
print('total words:',tw)
print('percentage of negative words:',per_neg)
print('percentage of positive words:',per_pos)
print('difference:', d)
print('absolute diff. score:', pd)
print('relative diff. score:', rd)

positive: 169
negative: 109
total words: 14574
percentage of negative words: 0.0074790723205708795
percentage of positive words: 0.011595992864004392
difference: 60
proportional diff. score: 0.004116920543433511
relative diff. score: 0.2158273381294964

Extra: Word Occurances

In [50]:
pos_word.query("occurances != 0")

            pos_words  occurances
87            amazing           1
113        appreciate           1
118       appropriate           1
172         beautiful           5
194              best           3
224             brave           2
225           bravery           1
239         brilliant           1
292             clear           2
297            clears           5
298            clever           1
338   congratulations           1
364         correctly           1
391           darling           2
405            defeat           1
438         diligence           1
474              easy           1
516          eminence           1
547             enjoy           1
558            enough           5
624         excellent           1
630           excited           1
635          exciting           1
668              fair           1
695            faster           2
727              fine           1
782            gained           1
793              gems           1
808              glee           2
830              good           9
841          gracious           1
846          grateful           1
855             great           3
856          greatest           1
882             happy           1
890           harmony           1
902            helped           1
905              hero           1
920           honored           3
922            hooray           1
966        impressive           5
975        incredible           1
1012      interesting           1
1071             lead           1
1086             like          15
1088            likes           3
1096             love           2
1097            loved           1
1099           lovely           1
1112             luck           3
1116            lucky           1
1128            magic           6
1129          magical           2
1197             nice           5
1260           pardon           1
1269            peace           1
1281          perfect           3
1304         pleasure           1
1323         powerful           4
1329         precious           1
1344           pretty           2
1370          promise           1
1423            ready           2
1476           relief           1
1524           reward           1
1531            right          16
1552             safe           1
1567       satisfying           1
1636             soft           1
1650          sparkle           5
1699           strong           3
1775         talented           1
1790            thank           7
1818              top           1
1856       unaffected           1
1933          welcome           5
1934             well           6
1956             whoa           2
1977           wonder           1
1978        wonderful           3
1985             work           4
1995              wow           4

In [92]:
neg_word.query("occurances != 0")

          neg_words  occurances
33       accusation           1
76           afraid           2
245             bad           3
359           bleed           1
426           break           1
491         burning           2
598            cold           1
618     complicated           1
631        concerns           1
676      contagious           1
682        contempt           1
736        crashing           1
743           crazy           3
823       dangerous           2
838            dead           1
845           death           1
1065            die           2
1124       disaster           1
1168        disdain           1
1327      disturbed           1
1352          doubt           1
1372           drab           1
1395         drippy           1
1415           dumb           1
1422        dungeon           3
1521         excuse           3
1574           fall           1
1581        falling           1
1677          flair           1
1718        foolish           1
1937           hang           1
1948           hard           2
1978           hate           2
2043        hissing           1
2084           hurt           2
2115         ignore           1
2198         impose           1
2384       infected           1
2496      interrupt           1
2510        intrude           1
2612           joke           1
2625           kill           1
2632          knife           1
2716           lies           1
2747          loose           1
2750           lose           1
2915           miss           3
2916         missed           1
2920        mistake           1
2933  misunderstood           1
2991        mystery           1
3001          nasty           2
3047       nonsense           1
3092            odd           2
3128         ordeal           1
3140     outrageous           1
3213          panic           1
3294            pig           4
3295           pigs           3
3316           plot           1
3335           poor           3
3358   preposterous           1
3376         prison           1
3495         regret           1
3549         resent           1
3590     ridiculous           3
3610          rocky           1
3614         rotten           2
3706          scorn           1
3768          shake           1
3786      shipwreck           1
3815           sick           3
3820       sickness           2
3825          silly           2
3952          sorry           6
3999      squealing           1
4022         starve           1
4047          stink           2
4060        strange           2
4090         stuffy           1
4098          stunt           1
4157           sunk           1
4210          tease           1
4226       terrible           3
4319        treason           1
4327        trouble           1
4594          upset           1
4685          waste           1
4702          wedge           1
4715         wicked           1
4718           wild           2
4740          worry           1
4743          worse           1
4746          worst           1
4771          wrong           2